### PR TITLE
fixes #92 This adds a referer question to the application form.

### LINKED ISSUE #92: "How did you hear about hackEDU?"
Add this question to the application.

### PR DESCRIPTION
**Pull request by MaxWofford**

### CODE REVIEW

**Comment by zachlatta** [comment]
Is the confirmation email sent to applicants and the email sent to us updated with this new question as well?

**Comment by MaxWofford** [comment]
@zachlatta I thought it is. The email is generated from `@application`, which is defined as `@application = ClubApplication.new(club_application_params)` in club_applications_controller.rb. The `@application` is fed directly into the mailer:
`       ClubApplicationMailer.applicant_confirmation(@application).deliver
         ClubApplicationMailer.admin_notification(@application).deliver`

**Comment by MaxWofford** [comment]
@zachlatta Is there a place I have to explicitly add this field to the mailer?

**Comment by zachlatta** [comment]
Ouch... those tests shouldn't have passed. Looks like we have some improvements we need to make!

Yeah... we should have to add the field to https://github.com/hackedu/website/blob/master/app/views/club_applications/_club_application.text.erb.

**Comment by MaxWofford** [comment]
screenshot 2015-05-31 at 2 36 56 pm
@zachlatta That's part of the PR

**Comment by zachlatta** [comment]
Oh man I'm dumb, nice.

**Comment by zachlatta** [comment]
Can we delete the branch?

**Pull request merged**
