### PR TITLE
fixes #94

### LINKED ISSUE #94: define "hacker" + larger vision (enabling people who build stuff)
More explicitly defining these things may help general-knowledge viewers understand our program.

### PR DESCRIPTION
**Pull request by MaxWofford**

### CODE REVIEW

**Comment by MaxWofford** [comment]
@jonleung @zachlatta Thoughts on this definition?

**Comment by zachlatta** [comment]
What if we just did

    hacker - Someone who creates what they see missing in the world

**Comment by MaxWofford** [comment]
Nice and simple :+1:

**Comment by zachlatta** [comment]
Cool, can you update the PR? Make sure to include a period in the definition/make it grammatically correct.

**Comment by MaxWofford** [comment]
screenshot 2015-05-31 at 1 07 16 pm

Ready for merge @zachlatta

**Comment by zachlatta** [comment]
Actually... going to go ahead and revert this as discussed on our call.

**Pull request merged**
