### PR TITLE
Auto-deploy from CI

### PR DESCRIPTION
**Pull request by zachlatta**
This PR enables automatic deployment from CircleCI, closing #131.

@MaxWofford can you review/merge this when you have a chance?

### CODE REVIEW

**Comment by MaxWofford** [comment]
@zachlatta Ummm. This is a bit over my head. Any good references to read up on this sort of thing?

**Comment by MaxWofford** [comment]
Merging for now because f it ship it

**Comment by zachlatta** [comment]
Well, the build seems to have not broken, so that's always a good thing.

**Comment by zachlatta** [comment]
Uhh...

recorded

**Comment by MaxWofford** [comment]
That's the power of http://quickme.me!

**Comment by zachlatta** [comment]
Non-deterministic images – I love it.

On Sat, Aug 22, 2015 at 10:54 PM, Max Wofford <notifications@github.com>
wrote:

> That's the power of http://quickme.me!
>
>
> <https://camo.githubusercontent.com/8d1e70b6a1ae6537f17aedca21b1ad6a46861da0/687474703a2f2f63646e2e6d656d652e616d2f696e7374616e6365732f35343632333438372e6a7067>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/website/pull/143#issuecomment-133790506>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Pull request merged**
