### PR TITLE
Add Dave to team page and sort it alphabetically.

### PR DESCRIPTION
**Pull request by zachlatta**
Still a WIP, need to replace @hellyeah's bio with a real one (right now it's just a copy of @MaxWofford's).

### CODE REVIEW

**Comment by MaxWofford** [comment]
@zachlatta Feel free to assign me when it is ready for merge!

**Comment by MaxWofford** [comment]
@hellyeah If you have a bio for the website, please comment it here or add it to the PR.

**Comment by jonleung** [comment]
@hellyeah poke! Let's get you on the website!

**Comment by hellyeah** [comment]
"Dave studies hybrid online/offline communities. Before joining hackEDU, he traveled to over 40 universities to help spread the hackathon movement."

**Comment by zachlatta** [comment]
Should be good to go!

**Comment by MaxWofford** [comment]
Thanks for the contribution!

screenshot from 2015-11-06 20 33 13

**Pull request merged**
