### PR TITLE
Send emails from 'hackEDU Team <team@hackedu.us>'

### PR DESCRIPTION
**Pull request by zachlatta**

### CODE REVIEW

**Comment by zachlatta** [comment]
@MaxWofford can you review this?

**Comment by MaxWofford** [comment]
@zachlatta Do you think this will make it less personal?

**Comment by zachlatta** [comment]
Yup, but I think it's also more authentic to make it more clear that the
email is from the team and not to me directly (and they can see it's
from the team anyways, because it's from `team@hackedu.us`).

We'll individually respond to each application, to make it more personal
(as we have been doing).

**Comment by MaxWofford** [comment]
@zachlatta Do you need to update `club_applications_controller_spec.rb`?

sauce: https://github.com/hackedu/website/pull/63/files

**Comment by zachlatta** [comment]
oh noes. we have issues with our tests. those should not have passed.

these must be resolved.

**Comment by MaxWofford** [comment]
@zachlatta ping

**Comment by zachlatta** [comment]
Yeah, will try to get to this today. No guarantees.

**Comment by MaxWofford** [comment]
Removing the assignment until the PR is updated. @zachlatta

**Comment by MaxWofford** [comment]
All test good. No results from grep of `Zach Latta` either.

**Comment by zachlatta** [comment]
Wait – didn't we agree those tests shouldn't have passed and we need to add a test to fix them?

**Comment by MaxWofford** [comment]
@zachlatta @#$%. Going to revert that.

**Comment by MaxWofford** [comment]
@zachlatta Or would you like to submit an issue for that?

**Comment by zachlatta** [comment]
Let's ago ahead and revert for now and open a new PR.

**Pull request merged**
