### PR TITLE
Redesign team page and add advisors

### PR DESCRIPTION
**Pull request by zachlatta**
This PR redesigns the team page to be a bit friendlier on the eyes and adds our advisors to the team page, per #139.

screencapture-localhost-3000-team-1440631731437

Do note: this only adds Pierre, Cary, and Tom from #139. I need to reach out to our other advisors to get headshots and descriptions. I created #148 to track this.

@MaxWofford can you review/merge this when you have the chance?

### CODE REVIEW

**Comment by MaxWofford** [comment]
@zachlatta Would it be better if I reviewed this for now, then merged once you get #148 finished and added to the PR?

**Comment by MaxWofford** [comment]
@zachlatta Do the advisers need to be in any particular order? If not, let's make it alphabetical.

**Comment by zachlatta** [comment]
Nope, they don't. Going to make it alphabetical now.

**Comment by zachlatta** [comment]
Updated the advisors commit. Here's what it looks like now:

screencapture-localhost-3000-team-1440632990188

**Comment by MaxWofford** [comment]
:+1: @zachlatta

**Pull request merged**
